-- Initial schema: user accounts and per-user health settings.
--
-- Conventions:
--   * Every table carries created_at / updated_at / deleted_at.
--   * Deletion is soft: deleted_at is NULL while the row is active.
--   * Public-facing identifiers are uuid; internal rows use bigint.
--   * updated_at is maintained by a trigger (set_updated_at) so every
--     code path keeps it correct.

-- migrate:up

CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'Trigger function that stamps updated_at on every UPDATE.';

CREATE TABLE users (
    id            uuid PRIMARY KEY,
    first_name    text NOT NULL,
    last_name     text NOT NULL,
    email         text NOT NULL,
    password_hash text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz NULL
);

CREATE UNIQUE INDEX users_email_key ON users (email);
CREATE INDEX users_created_at_idx ON users (created_at);

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE users IS
    'Application accounts. Email is stored normalized (trimmed, lowercase) and unique.';
COMMENT ON COLUMN users.id IS
    'Public identifier for the account (UUIDv4, generated by the API).';
COMMENT ON COLUMN users.email IS
    'Login email. Normalized to lowercase and trimmed before storage; case-insensitive by construction.';
COMMENT ON COLUMN users.password_hash IS
    'argon2id hash of the account password. The plaintext password is never stored.';
COMMENT ON COLUMN users.deleted_at IS
    'Soft delete timestamp. NULL means the account is active.';

CREATE TABLE user_profiles (
    user_id            uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    max_heart_rate     integer NULL CHECK (max_heart_rate > 0 AND max_heart_rate <= 300),
    resting_heart_rate integer NULL CHECK (resting_heart_rate > 0 AND resting_heart_rate <= 300),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz NULL
);

CREATE TRIGGER user_profiles_set_updated_at
    BEFORE UPDATE ON user_profiles
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE user_profiles IS
    'Per-user health settings. Drives heart-rate zone computation and future estimates.';
COMMENT ON COLUMN user_profiles.max_heart_rate IS
    'User maximum heart rate in bpm. Used to derive the five training zones.';
COMMENT ON COLUMN user_profiles.resting_heart_rate IS
    'User resting heart rate in bpm. Used for future readiness/zone refinements.';

-- migrate:down

DROP TRIGGER IF EXISTS user_profiles_set_updated_at ON user_profiles;
DROP TRIGGER IF EXISTS users_set_updated_at ON users;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS set_updated_at();
