-- Identifier convention (AGENTS.md): every non-reference table has an int
-- `id` primary key; rows that are publicly identified carry a `uuid` column
-- (unique, v4) which the API exposes as the public "id".
--
-- This migrates the existing uuid-PK tables: the old PK-uuid column is
-- renamed to `uuid` and a new int `id` becomes the primary key. Dropping
-- the old PK requires temporarily dropping the incoming foreign keys
-- (Postgres keeps one PK per table and an FK cannot outlive its target
-- constraint); they are re-added against the public `uuid` column.
-- `strength_exercise_sets` (already int-PK) gains the public `uuid`.

-- migrate:up

-- strength_exercise_sets already has an int PK; give it the public uuid
-- (first IntIdUuidModel table; sets will be referenced by URL).
ALTER TABLE strength_exercise_sets ADD COLUMN uuid uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE strength_exercise_sets ADD CONSTRAINT strength_exercise_sets_uuid_key UNIQUE (uuid);

COMMENT ON COLUMN strength_exercise_sets.uuid IS
    'Public identifier (UUIDv4): used in URLs and the API JSON "id" field.';

-- 1:1 satellites and the profile: the uuid FK was the PK; it becomes an
-- int PK with the uuid FK kept as a unique column. Nothing references
-- these PKs, so no FK surgery is needed.
ALTER TABLE user_profiles ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_pkey;
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);

ALTER TABLE activity_hr_zones ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE activity_hr_zones DROP CONSTRAINT activity_hr_zones_pkey;
ALTER TABLE activity_hr_zones ADD CONSTRAINT activity_hr_zones_pkey PRIMARY KEY (id);
ALTER TABLE activity_hr_zones ADD CONSTRAINT activity_hr_zones_activity_id_key UNIQUE (activity_id);

ALTER TABLE running_activity ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE running_activity DROP CONSTRAINT running_activity_pkey;
ALTER TABLE running_activity ADD CONSTRAINT running_activity_pkey PRIMARY KEY (id);
ALTER TABLE running_activity ADD CONSTRAINT running_activity_activity_id_key UNIQUE (activity_id);

ALTER TABLE cycling_activity ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE cycling_activity DROP CONSTRAINT cycling_activity_pkey;
ALTER TABLE cycling_activity ADD CONSTRAINT cycling_activity_pkey PRIMARY KEY (id);
ALTER TABLE cycling_activity ADD CONSTRAINT cycling_activity_activity_id_key UNIQUE (activity_id);

ALTER TABLE rowing_activity ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE rowing_activity DROP CONSTRAINT rowing_activity_pkey;
ALTER TABLE rowing_activity ADD CONSTRAINT rowing_activity_pkey PRIMARY KEY (id);
ALTER TABLE rowing_activity ADD CONSTRAINT rowing_activity_activity_id_key UNIQUE (activity_id);

ALTER TABLE strength_activity ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE strength_activity DROP CONSTRAINT strength_activity_pkey;
ALTER TABLE strength_activity ADD CONSTRAINT strength_activity_pkey PRIMARY KEY (id);
ALTER TABLE strength_activity ADD CONSTRAINT strength_activity_activity_id_key UNIQUE (activity_id);

COMMENT ON COLUMN user_profiles.id IS 'Internal integer primary key.';
COMMENT ON COLUMN activity_hr_zones.id IS 'Internal integer primary key.';
COMMENT ON COLUMN running_activity.id IS 'Internal integer primary key.';
COMMENT ON COLUMN cycling_activity.id IS 'Internal integer primary key.';
COMMENT ON COLUMN rowing_activity.id IS 'Internal integer primary key.';
COMMENT ON COLUMN strength_activity.id IS 'Internal integer primary key.';

-- activities: rename the PK-uuid column, drop the incoming FKs and the old
-- PK, install the int PK, then re-add the FKs against activities (uuid).
ALTER TABLE activities RENAME COLUMN id TO uuid;

ALTER TABLE activity_hr_zones DROP CONSTRAINT activity_hr_zones_activity_id_fkey;
ALTER TABLE activity_splits DROP CONSTRAINT activity_splits_activity_id_fkey;
ALTER TABLE activity_trackpoints DROP CONSTRAINT activity_trackpoints_activity_id_fkey;
ALTER TABLE cycling_activity DROP CONSTRAINT cycling_activity_activity_id_fkey;
ALTER TABLE rowing_activity DROP CONSTRAINT rowing_activity_activity_id_fkey;
ALTER TABLE running_activity DROP CONSTRAINT running_activity_activity_id_fkey;
ALTER TABLE strength_activity DROP CONSTRAINT strength_activity_activity_id_fkey;
ALTER TABLE strength_exercise_sets DROP CONSTRAINT strength_exercise_sets_activity_id_fkey;

ALTER TABLE activities DROP CONSTRAINT activities_pkey;
ALTER TABLE activities ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE activities ADD CONSTRAINT activities_pkey PRIMARY KEY (id);
ALTER TABLE activities ADD CONSTRAINT activities_uuid_key UNIQUE (uuid);

ALTER TABLE activity_hr_zones ADD CONSTRAINT activity_hr_zones_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE activity_splits ADD CONSTRAINT activity_splits_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE activity_trackpoints ADD CONSTRAINT activity_trackpoints_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE cycling_activity ADD CONSTRAINT cycling_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE rowing_activity ADD CONSTRAINT rowing_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE running_activity ADD CONSTRAINT running_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE strength_activity ADD CONSTRAINT strength_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;
ALTER TABLE strength_exercise_sets ADD CONSTRAINT strength_exercise_sets_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (uuid) ON DELETE CASCADE;

COMMENT ON COLUMN activities.id IS 'Internal integer primary key.';
COMMENT ON COLUMN activities.uuid IS
    'Public identifier (UUIDv4): used in URLs, JWTs, and the API JSON "id" field.';

-- users: same dance with its two incoming FKs.
ALTER TABLE users RENAME COLUMN id TO uuid;

ALTER TABLE activities DROP CONSTRAINT activities_user_id_fkey;
ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_user_id_fkey;

ALTER TABLE users DROP CONSTRAINT users_pkey;
ALTER TABLE users ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT users_uuid_key UNIQUE (uuid);

ALTER TABLE activities ADD CONSTRAINT activities_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (uuid) ON DELETE CASCADE;
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (uuid) ON DELETE CASCADE;

COMMENT ON COLUMN users.id IS 'Internal integer primary key.';
COMMENT ON COLUMN users.uuid IS
    'Public identifier (UUIDv4): used in URLs, JWTs, and the API JSON "id" field.';

-- migrate:down

ALTER TABLE activities DROP CONSTRAINT activities_user_id_fkey;
ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_user_id_fkey;
ALTER TABLE users DROP CONSTRAINT users_pkey;
ALTER TABLE users DROP CONSTRAINT users_uuid_key;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users RENAME COLUMN uuid TO id;
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE activities ADD CONSTRAINT activities_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE activity_hr_zones DROP CONSTRAINT activity_hr_zones_activity_id_fkey;
ALTER TABLE activity_splits DROP CONSTRAINT activity_splits_activity_id_fkey;
ALTER TABLE activity_trackpoints DROP CONSTRAINT activity_trackpoints_activity_id_fkey;
ALTER TABLE cycling_activity DROP CONSTRAINT cycling_activity_activity_id_fkey;
ALTER TABLE rowing_activity DROP CONSTRAINT rowing_activity_activity_id_fkey;
ALTER TABLE running_activity DROP CONSTRAINT running_activity_activity_id_fkey;
ALTER TABLE strength_activity DROP CONSTRAINT strength_activity_activity_id_fkey;
ALTER TABLE strength_exercise_sets DROP CONSTRAINT strength_exercise_sets_activity_id_fkey;
ALTER TABLE activities DROP CONSTRAINT activities_pkey;
ALTER TABLE activities DROP CONSTRAINT activities_uuid_key;
ALTER TABLE activities DROP COLUMN id;
ALTER TABLE activities RENAME COLUMN uuid TO id;
ALTER TABLE activities ADD CONSTRAINT activities_pkey PRIMARY KEY (id);
ALTER TABLE activity_hr_zones ADD CONSTRAINT activity_hr_zones_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE activity_splits ADD CONSTRAINT activity_splits_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE activity_trackpoints ADD CONSTRAINT activity_trackpoints_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE cycling_activity ADD CONSTRAINT cycling_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE rowing_activity ADD CONSTRAINT rowing_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE running_activity ADD CONSTRAINT running_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE strength_activity ADD CONSTRAINT strength_activity_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;
ALTER TABLE strength_exercise_sets ADD CONSTRAINT strength_exercise_sets_activity_id_fkey
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE;

ALTER TABLE strength_activity DROP CONSTRAINT strength_activity_activity_id_key;
ALTER TABLE strength_activity DROP CONSTRAINT strength_activity_pkey;
ALTER TABLE strength_activity DROP COLUMN id;
ALTER TABLE strength_activity ADD CONSTRAINT strength_activity_pkey PRIMARY KEY (activity_id);

ALTER TABLE rowing_activity DROP CONSTRAINT rowing_activity_activity_id_key;
ALTER TABLE rowing_activity DROP CONSTRAINT rowing_activity_pkey;
ALTER TABLE rowing_activity DROP COLUMN id;
ALTER TABLE rowing_activity ADD CONSTRAINT rowing_activity_pkey PRIMARY KEY (activity_id);

ALTER TABLE cycling_activity DROP CONSTRAINT cycling_activity_activity_id_key;
ALTER TABLE cycling_activity DROP CONSTRAINT cycling_activity_pkey;
ALTER TABLE cycling_activity DROP COLUMN id;
ALTER TABLE cycling_activity ADD CONSTRAINT cycling_activity_pkey PRIMARY KEY (activity_id);

ALTER TABLE running_activity DROP CONSTRAINT running_activity_activity_id_key;
ALTER TABLE running_activity DROP CONSTRAINT running_activity_pkey;
ALTER TABLE running_activity DROP COLUMN id;
ALTER TABLE running_activity ADD CONSTRAINT running_activity_pkey PRIMARY KEY (activity_id);

ALTER TABLE activity_hr_zones DROP CONSTRAINT activity_hr_zones_activity_id_key;
ALTER TABLE activity_hr_zones DROP CONSTRAINT activity_hr_zones_pkey;
ALTER TABLE activity_hr_zones DROP COLUMN id;
ALTER TABLE activity_hr_zones ADD CONSTRAINT activity_hr_zones_pkey PRIMARY KEY (activity_id);

ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_user_id_key;
ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_pkey;
ALTER TABLE user_profiles DROP COLUMN id;
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id);

ALTER TABLE strength_exercise_sets DROP CONSTRAINT strength_exercise_sets_uuid_key;
ALTER TABLE strength_exercise_sets DROP COLUMN uuid;
