-- M13a: user-configurable heart-rate zones.
--   * ``user_profiles`` gains a date of birth (for the age-derived max HR,
--     220 - current_age) and four optional custom zone thresholds.
--   * ``zone_sources``: reference table for the reference a zone snapshot was
--     computed from (custom / max_heart_rate / age).
--   * ``activity_zone_snapshots``: per-activity, versioned zone results. Each
--     row records the reference used and the resulting per-zone seconds; at
--     most one live (non-soft-deleted) row exists per activity. When a zone
--     result is superseded, the old row is soft-deleted (kept for history),
--     never destroyed.

-- migrate:up

ALTER TABLE user_profiles
    ADD COLUMN date_of_birth         date    NULL,
    ADD COLUMN custom_zone_1_top_bpm integer NULL CHECK (custom_zone_1_top_bpm > 0 AND custom_zone_1_top_bpm <= 300),
    ADD COLUMN custom_zone_2_top_bpm integer NULL CHECK (custom_zone_2_top_bpm > 0 AND custom_zone_2_top_bpm <= 300),
    ADD COLUMN custom_zone_3_top_bpm integer NULL CHECK (custom_zone_3_top_bpm > 0 AND custom_zone_3_top_bpm <= 300),
    ADD COLUMN custom_zone_4_top_bpm integer NULL CHECK (custom_zone_4_top_bpm > 0 AND custom_zone_4_top_bpm <= 300);

COMMENT ON COLUMN user_profiles.date_of_birth IS
    'Date of birth. The age-derived max heart rate is 220 - current_age, computed from this column.';
COMMENT ON COLUMN user_profiles.custom_zone_1_top_bpm IS
    'Top of zone 1 in bpm, for user-defined custom zones. Set only as a complete strictly-ascending set with zones 2-4; NULL when custom zones are not in use.';
COMMENT ON COLUMN user_profiles.custom_zone_2_top_bpm IS
    'Top of zone 2 in bpm (custom zones). See custom_zone_1_top_bpm.';
COMMENT ON COLUMN user_profiles.custom_zone_3_top_bpm IS
    'Top of zone 3 in bpm (custom zones). See custom_zone_1_top_bpm.';
COMMENT ON COLUMN user_profiles.custom_zone_4_top_bpm IS
    'Top of zone 4 in bpm (custom zones); zone 5 is everything above it. See custom_zone_1_top_bpm.';

CREATE TABLE zone_sources (
    value         text PRIMARY KEY,
    description   text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE zone_sources IS
    'Reference table of the reference a heart-rate zone snapshot was computed from. Rows are seeded and immutable.';
COMMENT ON COLUMN zone_sources.value IS
    'Canonical source code (custom, max_heart_rate, age); the public API value and FK target.';
COMMENT ON COLUMN zone_sources.description IS
    'Human-readable label for UI display (e.g. Age (220 - age)).';

INSERT INTO zone_sources (value, description) VALUES
    ('custom',         'Custom zones'),
    ('max_heart_rate', 'Max heart rate'),
    ('age',            'Age (220 - age)');

CREATE TABLE activity_zone_snapshots (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id           uuid NOT NULL REFERENCES activities (uuid) ON DELETE CASCADE,
    source                text NOT NULL REFERENCES zone_sources (value),
    max_heart_rate        integer NULL CHECK (max_heart_rate > 0 AND max_heart_rate <= 300),
    age                   integer NULL CHECK (age > 0 AND age <= 120),
    custom_zone_1_top_bpm integer NULL CHECK (custom_zone_1_top_bpm > 0 AND custom_zone_1_top_bpm <= 300),
    custom_zone_2_top_bpm integer NULL CHECK (custom_zone_2_top_bpm > 0 AND custom_zone_2_top_bpm <= 300),
    custom_zone_3_top_bpm integer NULL CHECK (custom_zone_3_top_bpm > 0 AND custom_zone_3_top_bpm <= 300),
    custom_zone_4_top_bpm integer NULL CHECK (custom_zone_4_top_bpm > 0 AND custom_zone_4_top_bpm <= 300),
    zone_1_seconds        integer NOT NULL DEFAULT 0 CHECK (zone_1_seconds >= 0),
    zone_2_seconds        integer NOT NULL DEFAULT 0 CHECK (zone_2_seconds >= 0),
    zone_3_seconds        integer NOT NULL DEFAULT 0 CHECK (zone_3_seconds >= 0),
    zone_4_seconds        integer NOT NULL DEFAULT 0 CHECK (zone_4_seconds >= 0),
    zone_5_seconds        integer NOT NULL DEFAULT 0 CHECK (zone_5_seconds >= 0),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    deleted_at            timestamptz NULL
);

-- At most one live (current) zone snapshot per activity; superseded rows are
-- soft-deleted and remain for history.
CREATE UNIQUE INDEX activity_zone_snapshots_current_key
    ON activity_zone_snapshots (activity_id)
    WHERE deleted_at IS NULL;
COMMENT ON INDEX activity_zone_snapshots_current_key IS
    'A single live zone snapshot per activity; older ones are soft-deleted, not removed.';

CREATE TRIGGER activity_zone_snapshots_set_updated_at
    BEFORE UPDATE ON activity_zone_snapshots
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE activity_zone_snapshots IS
    'Versioned per-activity heart-rate zone results. Each row is one computation: the reference used (source + its values) and the resulting seconds per zone. The live row is the one with deleted_at NULL.';
COMMENT ON COLUMN activity_zone_snapshots.id IS 'Internal integer primary key.';
COMMENT ON COLUMN activity_zone_snapshots.activity_id IS 'FK to activities (uuid); the snapshot''s activity.';
COMMENT ON COLUMN activity_zone_snapshots.source IS 'Where this computation''s reference came from; FK to zone_sources.value (custom, max_heart_rate, age).';
COMMENT ON COLUMN activity_zone_snapshots.max_heart_rate IS 'Effective max heart rate in bpm, when source is max_heart_rate or age; NULL for custom.';
COMMENT ON COLUMN activity_zone_snapshots.age IS 'The user''s age in years at computation time, when source is age; NULL otherwise.';
COMMENT ON COLUMN activity_zone_snapshots.custom_zone_1_top_bpm IS 'Top of zone 1 in bpm, when source is custom; NULL otherwise.';
COMMENT ON COLUMN activity_zone_snapshots.custom_zone_2_top_bpm IS 'Top of zone 2 in bpm (custom). See custom_zone_1_top_bpm.';
COMMENT ON COLUMN activity_zone_snapshots.custom_zone_3_top_bpm IS 'Top of zone 3 in bpm (custom). See custom_zone_1_top_bpm.';
COMMENT ON COLUMN activity_zone_snapshots.custom_zone_4_top_bpm IS 'Top of zone 4 in bpm (custom); zone 5 is above it. See custom_zone_1_top_bpm.';
COMMENT ON COLUMN activity_zone_snapshots.zone_1_seconds IS 'Seconds spent in zone 1 for this computation.';
COMMENT ON COLUMN activity_zone_snapshots.zone_2_seconds IS 'Seconds spent in zone 2 for this computation.';
COMMENT ON COLUMN activity_zone_snapshots.zone_3_seconds IS 'Seconds spent in zone 3 for this computation.';
COMMENT ON COLUMN activity_zone_snapshots.zone_4_seconds IS 'Seconds spent in zone 4 for this computation.';
COMMENT ON COLUMN activity_zone_snapshots.zone_5_seconds IS 'Seconds spent in zone 5 for this computation.';
COMMENT ON COLUMN activity_zone_snapshots.created_at IS 'When this zone snapshot was computed (also the audit created timestamp).';
COMMENT ON COLUMN activity_zone_snapshots.deleted_at IS 'Soft delete: set when a newer snapshot supersedes this one; NULL means it is the current result.';

-- migrate:down

DROP TRIGGER IF EXISTS activity_zone_snapshots_set_updated_at ON activity_zone_snapshots;
DROP INDEX IF EXISTS activity_zone_snapshots_current_key;
DROP TABLE IF EXISTS activity_zone_snapshots;

DROP TABLE IF EXISTS zone_sources;

ALTER TABLE user_profiles
    DROP COLUMN date_of_birth,
    DROP COLUMN custom_zone_1_top_bpm,
    DROP COLUMN custom_zone_2_top_bpm,
    DROP COLUMN custom_zone_3_top_bpm,
    DROP COLUMN custom_zone_4_top_bpm;
