-- Activity storage: the activities table, its per-sample trackpoints,
-- computed splits, heart-rate zone totals, and per-sport metric tables.
--
-- Design notes:
--   * ``activities`` holds every metric that applies to most sports.
--     Metrics that only make sense for one sport live in a 1:1
--     ``<sport>_activity`` table (running_activity, cycling_activity, ...).
--   * ``activity_trackpoints`` is bulk-loaded immutable data, so it carries
--     no audit columns (the "most tables" exception, documented here).
--   * Splits are precomputed for both km and miles at import time.

-- migrate:up

CREATE TABLE activities (
    id                 uuid PRIMARY KEY,
    user_id            uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sport_type         text NOT NULL CHECK (sport_type IN (
                          'running', 'cycling', 'rowing', 'strength',
                          'yoga', 'hiking', 'walking', 'swimming', 'other'
                      )),
    name               text NOT NULL,
    description        text NULL,
    started_at         timestamptz NOT NULL,
    ended_at           timestamptz NOT NULL,
    duration_seconds   integer NOT NULL CHECK (duration_seconds >= 0),
    moving_seconds     integer NULL CHECK (moving_seconds IS NULL OR moving_seconds >= 0),
    distance_m         double precision NULL CHECK (distance_m IS NULL OR distance_m >= 0),
    calories_kcal      double precision NULL CHECK (calories_kcal IS NULL OR calories_kcal >= 0),
    elevation_gain_m   double precision NULL CHECK (elevation_gain_m IS NULL OR elevation_gain_m >= 0),
    heart_rate_min_bpm integer NULL CHECK (heart_rate_min_bpm IS NULL OR heart_rate_min_bpm > 0),
    heart_rate_avg_bpm integer NULL CHECK (heart_rate_avg_bpm IS NULL OR heart_rate_avg_bpm > 0),
    heart_rate_max_bpm integer NULL CHECK (heart_rate_max_bpm IS NULL OR heart_rate_max_bpm > 0),
    cadence_avg_rpm    integer NULL CHECK (cadence_avg_rpm IS NULL OR cadence_avg_rpm > 0),
    source_format      text NOT NULL CHECK (source_format IN ('gpx', 'tcx', 'fit', 'apple_health')),
    original_filename  text NULL,
    file_path          text NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz NULL,
    CONSTRAINT activities_time_range CHECK (ended_at >= started_at)
);

CREATE INDEX activities_user_started_idx ON activities (user_id, started_at DESC);
CREATE INDEX activities_user_sport_idx ON activities (user_id, sport_type);

CREATE TRIGGER activities_set_updated_at
    BEFORE UPDATE ON activities
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE activities IS
    'Imported sport activities. Common metrics for all sports; sport-specific metrics live in <sport>_activity tables.';
COMMENT ON COLUMN activities.id IS
    'Public identifier (UUIDv4, generated by the API); used in URLs.';
COMMENT ON COLUMN activities.user_id IS
    'Owner of the activity. Every activity query is scoped to this user.';
COMMENT ON COLUMN activities.sport_type IS
    'Sport category; drives which <sport>_activity table and detail view apply.';
COMMENT ON COLUMN activities.name IS
    'Display name, from the file or user-chosen (e.g. "Morning Run").';
COMMENT ON COLUMN activities.started_at IS
    'Activity start, UTC.';
COMMENT ON COLUMN activities.ended_at IS
    'Activity end, UTC.';
COMMENT ON COLUMN activities.duration_seconds IS
    'Total elapsed time (ended_at - started_at).';
COMMENT ON COLUMN activities.moving_seconds IS
    'Time actually moving, when the source provides it (NULL otherwise).';
COMMENT ON COLUMN activities.distance_m IS
    'Total distance in meters (NULL for non-GPS sports like strength/yoga).';
COMMENT ON COLUMN activities.calories_kcal IS
    'Energy expenditure in kcal, from the file when available (NULL otherwise).';
COMMENT ON COLUMN activities.elevation_gain_m IS
    'Cumulative positive elevation gain in meters, when altitude data exists.';
COMMENT ON COLUMN activities.heart_rate_min_bpm IS 'Lowest recorded heart rate (bpm).' ;
COMMENT ON COLUMN activities.heart_rate_avg_bpm IS 'Average recorded heart rate (bpm).';
COMMENT ON COLUMN activities.heart_rate_max_bpm IS 'Highest recorded heart rate (bpm).';
COMMENT ON COLUMN activities.cadence_avg_rpm IS
    'Average cadence in revolutions/strides per minute, when the source provides it.';
COMMENT ON COLUMN activities.source_format IS
    'Format of the imported file: gpx, tcx, fit, or apple_health.';
COMMENT ON COLUMN activities.original_filename IS 'File name as uploaded (for display).';
COMMENT ON COLUMN activities.file_path IS
    'Storage path of the original file inside the uploads volume (for re-import/export).';

CREATE TABLE activity_trackpoints (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id    uuid NOT NULL REFERENCES activities (id) ON DELETE CASCADE,
    seq            integer NOT NULL CHECK (seq >= 0),
    recorded_at    timestamptz NULL,
    lat            double precision NULL CHECK (lat IS NULL OR (lat >= -90 AND lat <= 90)),
    lon            double precision NULL CHECK (lon IS NULL OR (lon >= -180 AND lon <= 180)),
    altitude_m     double precision NULL,
    heart_rate_bpm integer NULL CHECK (heart_rate_bpm IS NULL OR heart_rate_bpm > 0),
    cadence_rpm    integer NULL CHECK (cadence_rpm IS NULL OR cadence_rpm > 0),
    speed_mps      double precision NULL CHECK (speed_mps IS NULL OR speed_mps >= 0),
    power_w        integer NULL CHECK (power_w IS NULL OR power_w > 0),
    CONSTRAINT activity_trackpoints_activity_seq_unique UNIQUE (activity_id, seq)
);

CREATE INDEX activity_trackpoints_activity_idx ON activity_trackpoints (activity_id, seq);

COMMENT ON TABLE activity_trackpoints IS
    'Per-sample GPS/physiology data, one row per recorded sample. Immutable bulk data: no audit columns by design.';
COMMENT ON COLUMN activity_trackpoints.activity_id IS 'Owning activity.';
COMMENT ON COLUMN activity_trackpoints.seq IS 'Sample order within the activity (0-based).';
COMMENT ON COLUMN activity_trackpoints.recorded_at IS 'Sample time, UTC (NULL when the source omits it).';
COMMENT ON COLUMN activity_trackpoints.lat IS 'WGS84 latitude (NULL for non-GPS samples).';
COMMENT ON COLUMN activity_trackpoints.lon IS 'WGS84 longitude (NULL for non-GPS samples).';
COMMENT ON COLUMN activity_trackpoints.altitude_m IS 'Altitude in meters above sea level, when available.';
COMMENT ON COLUMN activity_trackpoints.heart_rate_bpm IS 'Heart rate at this sample (bpm), when available.';
COMMENT ON COLUMN activity_trackpoints.cadence_rpm IS 'Cadence at this sample (rpm), when available.';
COMMENT ON COLUMN activity_trackpoints.speed_mps IS 'Ground speed in meters per second, when available.';
COMMENT ON COLUMN activity_trackpoints.power_w IS 'Power in watts (cycling/rowing), when available.';

CREATE TABLE activity_splits (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id        uuid NOT NULL REFERENCES activities (id) ON DELETE CASCADE,
    split_type         text NOT NULL CHECK (split_type IN ('km', 'mi')),
    split_index        integer NOT NULL CHECK (split_index >= 1),
    duration_seconds   integer NOT NULL CHECK (duration_seconds >= 0),
    pace_seconds       double precision NOT NULL CHECK (pace_seconds >= 0),
    heart_rate_avg_bpm integer NULL CHECK (heart_rate_avg_bpm IS NULL OR heart_rate_avg_bpm > 0),
    cadence_avg_rpm    integer NULL CHECK (cadence_avg_rpm IS NULL OR cadence_avg_rpm > 0),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz NULL,
    CONSTRAINT activity_splits_activity_type_index_unique
        UNIQUE (activity_id, split_type, split_index)
);

CREATE INDEX activity_splits_activity_idx ON activity_splits (activity_id, split_type, split_index);

CREATE TRIGGER activity_splits_set_updated_at
    BEFORE UPDATE ON activity_splits
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE activity_splits IS
    'Precomputed per-distance splits (kilometers and miles), one row per split. Computed from trackpoints at import time.';
COMMENT ON COLUMN activity_splits.split_type IS 'Unit of the split distance: km or mi.';
COMMENT ON COLUMN activity_splits.split_index IS '1-based ordinal of the split within its unit (1 = first km/mi).';
COMMENT ON COLUMN activity_splits.duration_seconds IS 'Time taken to cover this split.';
COMMENT ON COLUMN activity_splits.pace_seconds IS 'Pace for this split in seconds per km (or per mile).';

CREATE TABLE activity_hr_zones (
    activity_id    uuid PRIMARY KEY REFERENCES activities (id) ON DELETE CASCADE,
    zone_1_seconds integer NOT NULL DEFAULT 0 CHECK (zone_1_seconds >= 0),
    zone_2_seconds integer NOT NULL DEFAULT 0 CHECK (zone_2_seconds >= 0),
    zone_3_seconds integer NOT NULL DEFAULT 0 CHECK (zone_3_seconds >= 0),
    zone_4_seconds integer NOT NULL DEFAULT 0 CHECK (zone_4_seconds >= 0),
    zone_5_seconds integer NOT NULL DEFAULT 0 CHECK (zone_5_seconds >= 0),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz NULL
);

CREATE TRIGGER activity_hr_zones_set_updated_at
    BEFORE UPDATE ON activity_hr_zones
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE activity_hr_zones IS
    'Time spent in each of the five heart-rate zones (percent-of-max-HR zones), computed at import time.';
COMMENT ON COLUMN activity_hr_zones.zone_1_seconds IS
    'Seconds below 56% of max heart rate (warmup).';
COMMENT ON COLUMN activity_hr_zones.zone_2_seconds IS
    'Seconds at 56-63% of max heart rate (easy).';
COMMENT ON COLUMN activity_hr_zones.zone_3_seconds IS
    'Seconds at 64-71% of max heart rate (tempo).';
COMMENT ON COLUMN activity_hr_zones.zone_4_seconds IS
    'Seconds at 72-80% of max heart rate (threshold).';
COMMENT ON COLUMN activity_hr_zones.zone_5_seconds IS
    'Seconds above 80% of max heart rate (VO2 max).';

-- Per-sport metric tables (1:1 with activities).

CREATE TABLE running_activity (
    activity_id        uuid PRIMARY KEY REFERENCES activities (id) ON DELETE CASCADE,
    avg_pace_s_per_km  double precision NULL CHECK (avg_pace_s_per_km IS NULL OR avg_pace_s_per_km >= 0),
    min_pace_s_per_km  double precision NULL CHECK (min_pace_s_per_km IS NULL OR min_pace_s_per_km >= 0),
    max_pace_s_per_km  double precision NULL CHECK (max_pace_s_per_km IS NULL OR max_pace_s_per_km >= 0),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz NULL
);

CREATE TRIGGER running_activity_set_updated_at
    BEFORE UPDATE ON running_activity
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE running_activity IS
    'Running-specific metrics for activities with sport_type = running.';
COMMENT ON COLUMN running_activity.avg_pace_s_per_km IS 'Average pace in seconds per kilometer.';
COMMENT ON COLUMN running_activity.min_pace_s_per_km IS 'Fastest per-kilometer pace in seconds (NULL when no GPS splits).';
COMMENT ON COLUMN running_activity.max_pace_s_per_km IS 'Slowest per-kilometer pace in seconds (NULL when no GPS splits).';

CREATE TABLE cycling_activity (
    activity_id   uuid PRIMARY KEY REFERENCES activities (id) ON DELETE CASCADE,
    power_avg_w   integer NULL CHECK (power_avg_w IS NULL OR power_avg_w > 0),
    power_max_w   integer NULL CHECK (power_max_w IS NULL OR power_max_w > 0),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz NULL
);

CREATE TRIGGER cycling_activity_set_updated_at
    BEFORE UPDATE ON cycling_activity
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE cycling_activity IS
    'Cycling-specific metrics for activities with sport_type = cycling.';
COMMENT ON COLUMN cycling_activity.power_avg_w IS 'Average power in watts, from the file or trackpoints.';
COMMENT ON COLUMN cycling_activity.power_max_w IS 'Maximum power in watts, from the file or trackpoints.';

CREATE TABLE rowing_activity (
    activity_id          uuid PRIMARY KEY REFERENCES activities (id) ON DELETE CASCADE,
    stroke_rate_avg_spm  integer NULL CHECK (stroke_rate_avg_spm IS NULL OR stroke_rate_avg_spm > 0),
    stroke_rate_min_spm  integer NULL CHECK (stroke_rate_min_spm IS NULL OR stroke_rate_min_spm > 0),
    stroke_rate_max_spm  integer NULL CHECK (stroke_rate_max_spm IS NULL OR stroke_rate_max_spm > 0),
    split_500m_seconds   double precision NULL CHECK (split_500m_seconds IS NULL OR split_500m_seconds >= 0),
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    deleted_at           timestamptz NULL
);

CREATE TRIGGER rowing_activity_set_updated_at
    BEFORE UPDATE ON rowing_activity
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE rowing_activity IS
    'Rowing-specific metrics for activities with sport_type = rowing.';
COMMENT ON COLUMN rowing_activity.stroke_rate_avg_spm IS 'Average stroke rate in strokes per minute.';
COMMENT ON COLUMN rowing_activity.stroke_rate_min_spm IS 'Slowest stroke rate (spmin).';
COMMENT ON COLUMN rowing_activity.stroke_rate_max_spm IS 'Fastest stroke rate (spmin).';
COMMENT ON COLUMN rowing_activity.split_500m_seconds IS
    'Average 500m split in seconds (the standard rowing pace metric), when distance data exists.';

CREATE TABLE strength_activity (
    activity_id      uuid PRIMARY KEY REFERENCES activities (id) ON DELETE CASCADE,
    total_sets       integer NOT NULL DEFAULT 0 CHECK (total_sets >= 0),
    total_exercises  integer NOT NULL DEFAULT 0 CHECK (total_exercises >= 0),
    total_weight_kg  double precision NULL CHECK (total_weight_kg IS NULL OR total_weight_kg >= 0),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz NULL
);

CREATE TRIGGER strength_activity_set_updated_at
    BEFORE UPDATE ON strength_activity
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE strength_activity IS
    'Strength-training summary metrics for activities with sport_type = strength.';
COMMENT ON COLUMN strength_activity.total_sets IS 'Total number of sets across all exercises.';
COMMENT ON COLUMN strength_activity.total_exercises IS 'Number of distinct exercises.';
COMMENT ON COLUMN strength_activity.total_weight_kg IS 'Total lifted volume in kg (sum of set weight x reps), when known.';

CREATE TABLE strength_exercise_sets (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id    uuid NOT NULL REFERENCES activities (id) ON DELETE CASCADE,
    exercise_name  text NOT NULL,
    set_index      integer NOT NULL CHECK (set_index >= 1),
    reps           integer NULL CHECK (reps IS NULL OR reps > 0),
    weight_kg      double precision NULL CHECK (weight_kg IS NULL OR weight_kg >= 0),
    rest_seconds   integer NULL CHECK (rest_seconds IS NULL OR rest_seconds >= 0)
);

CREATE INDEX strength_exercise_sets_activity_idx ON strength_exercise_sets (activity_id);

COMMENT ON TABLE strength_exercise_sets IS
    'Per-set detail for strength activities. Immutable bulk data: no audit columns by design.';
COMMENT ON COLUMN strength_exercise_sets.exercise_name IS 'Exercise as recorded in the source (e.g. "Squat").';
COMMENT ON COLUMN strength_exercise_sets.set_index IS '1-based set number within the exercise.';
COMMENT ON COLUMN strength_exercise_sets.reps IS 'Reps performed (NULL for time-based sets).';
COMMENT ON COLUMN strength_exercise_sets.weight_kg IS 'Load in kilograms (NULL for bodyweight sets).';
COMMENT ON COLUMN strength_exercise_sets.rest_seconds IS 'Rest after the set, when the source provides it.';

-- migrate:down

DROP TABLE IF EXISTS strength_exercise_sets;
DROP TABLE IF EXISTS strength_activity;
DROP TABLE IF EXISTS rowing_activity;
DROP TABLE IF EXISTS cycling_activity;
DROP TABLE IF EXISTS running_activity;
DROP TABLE IF EXISTS activity_hr_zones;
DROP TABLE IF EXISTS activity_splits;
DROP TABLE IF EXISTS activity_trackpoints;
DROP TABLE IF EXISTS activities;
