-- Heart-rate zones are no longer stored (M12). They are computed at view
-- time from the activity's trackpoints, relative to the viewer's profile
-- max heart rate: a zone is relative to a *person*, not to the activity, so
-- the import-time snapshot went stale whenever the profile max HR was set
-- or changed (the old fallback to the activity's own max HR was
-- misleading — it anchored 100% at the activity's peak and pushed almost
-- every effort into the top zones).
--
-- The table is dropped; the trackpoints it was derived from are untouched
-- and now feed the view-time computation directly.

-- migrate:up

DROP TABLE activity_hr_zones;

-- migrate:down

CREATE TABLE activity_hr_zones (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id     uuid NOT NULL UNIQUE REFERENCES activities (uuid) ON DELETE CASCADE,
    zone_1_seconds  integer NOT NULL DEFAULT 0 CHECK (zone_1_seconds >= 0),
    zone_2_seconds  integer NOT NULL DEFAULT 0 CHECK (zone_2_seconds >= 0),
    zone_3_seconds  integer NOT NULL DEFAULT 0 CHECK (zone_3_seconds >= 0),
    zone_4_seconds  integer NOT NULL DEFAULT 0 CHECK (zone_4_seconds >= 0),
    zone_5_seconds  integer NOT NULL DEFAULT 0 CHECK (zone_5_seconds >= 0),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz NULL
);

CREATE TRIGGER activity_hr_zones_set_updated_at
    BEFORE UPDATE ON activity_hr_zones
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE activity_hr_zones IS
    'Time spent in each of the five heart-rate zones (percent-of-max-HR zones), computed at import time.';
COMMENT ON COLUMN activity_hr_zones.zone_1_seconds IS
    'Seconds below 56% of max heart rate (warmup).';
COMMENT ON COLUMN activity_hr_zones.zone_2_seconds IS
    'Seconds at 56-63% of max heart rate (easy).';
COMMENT ON COLUMN activity_hr_zones.zone_3_seconds IS
    'Seconds at 64-71% of max heart rate (tempo).';
COMMENT ON COLUMN activity_hr_zones.zone_4_seconds IS
    'Seconds at 72-80% of max heart rate (threshold).';
COMMENT ON COLUMN activity_hr_zones.zone_5_seconds IS
    'Seconds above 80% of max heart rate (VO2 max).';
