-- Self-service provider configuration (M11): the deployment's own OAuth
-- client credentials per provider, managed through the UI. The database is
-- the only source — the STRAVA_* environment variables no longer exist
-- (pre-1.0, so no legacy fallback is carried).
--
--   * ``server_settings`` is a small key/value table for deployment-level
--     (non-user) settings; its first tenant is the Fernet key used to
--     encrypt provider client secrets at rest.
--   * ``provider_credentials`` holds the deployment-wide OAuth client for
--     one provider (client id + encrypted client secret + optional label)
--     — one row per provider. Per-user connections remain in
--     ``provider_accounts``.
--   * ``provider_accounts.sync_since`` is the user-chosen inclusive lower
--     bound of the sync walk (M11e): only activities started at or after it
--     are imported. NULL means full history.

-- migrate:up

CREATE TABLE server_settings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         text NOT NULL UNIQUE,
    value       text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz NULL
);

CREATE TRIGGER server_settings_set_updated_at
    BEFORE UPDATE ON server_settings
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE server_settings IS
    'Deployment-level key/value settings (not per-user data). First tenant: the Fernet key (key = secret_key) used to encrypt provider client secrets at rest.';
COMMENT ON COLUMN server_settings.key IS
    'Setting name (unique), e.g. secret_key.';
COMMENT ON COLUMN server_settings.value IS
    'Setting value. Never returned by the API for secret settings.';

CREATE TABLE provider_credentials (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider      text NOT NULL REFERENCES providers (value),
    client_id     text NOT NULL,
    client_secret text NOT NULL,
    display_name  text NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz NULL,
    CONSTRAINT provider_credentials_provider_key UNIQUE (provider)
);

CREATE TRIGGER provider_credentials_set_updated_at
    BEFORE UPDATE ON provider_credentials
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE provider_credentials IS
    'The deployment''s own OAuth client credentials for one provider, configured via the UI (M11) instead of environment variables. One row per provider; per-user connections live in provider_accounts.';
COMMENT ON COLUMN provider_credentials.provider IS
    'FK to providers.value (e.g. strava); unique — one deployment-wide credential set per provider.';
COMMENT ON COLUMN provider_credentials.client_id IS
    'The provider app''s client id (not a secret; safe to display).';
COMMENT ON COLUMN provider_credentials.client_secret IS
    'The provider app''s client secret, encrypted at rest (Fernet; the key lives in server_settings). Never exposed via the API.';
COMMENT ON COLUMN provider_credentials.display_name IS
    'Optional human label for the provider app, for the UI (e.g. Homelab Strava).';

ALTER TABLE provider_accounts
    ADD COLUMN sync_since timestamptz NULL;

COMMENT ON COLUMN provider_accounts.sync_since IS
    'User-chosen inclusive lower bound of the sync walk: only activities started at or after this date are imported (NULL = full history). Set via the UI (M11d), applied by the sync walk (M11e). Survives reconnects — it is a user preference, not sync state.';

-- migrate:down

ALTER TABLE provider_accounts DROP COLUMN sync_since;
DROP TABLE provider_credentials;
DROP TABLE server_settings;
