-- M22b: user-uploaded activity images (local-first).
--   * ``image_sources`` reference table: where an image came from. Only
--     'uploaded' is seeded today; the parked Strava-fetch half adds its value
--     in a later migration. Reference-table rule: PK is the value, seeded and
--     immutable (no updated_at/deleted_at).
--   * ``activity_images``: one row per image attached to an activity. The
--     bytes live on disk under uploads/<user_id>/images/; this row is the
--     authoritative record (provenance, original filename, size). Soft delete.

-- migrate:up

CREATE TABLE image_sources (
    value         text PRIMARY KEY,
    description   text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE image_sources IS
    'Reference table of the origins an activity image can have. Seeded and immutable.';
COMMENT ON COLUMN image_sources.value IS
    'Canonical source code; the public API value and the FK target (e.g. uploaded).';
COMMENT ON COLUMN image_sources.description IS
    'Human-readable label for UI display (e.g. Uploaded).';

INSERT INTO image_sources (value, description) VALUES
    ('uploaded', 'Uploaded by the user');

CREATE TABLE activity_images (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              uuid NOT NULL UNIQUE,
    activity_id       uuid NOT NULL REFERENCES activities (uuid) ON DELETE CASCADE,
    source            text NOT NULL REFERENCES image_sources (value),
    original_filename text NULL,
    stored_name       text NOT NULL,
    source_url        text NULL,
    bytes             integer NOT NULL CHECK (bytes > 0),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    deleted_at        timestamptz NULL
);

COMMENT ON TABLE activity_images IS
    'Images attached to an activity (M22). The file bytes live on disk under uploads/<user_id>/images/; this row is the authoritative record. A soft-deleted image keeps its history but its file has been removed from disk.';
COMMENT ON COLUMN activity_images.uuid IS
    'Public identifier exposed by the API (generated by it).';
COMMENT ON COLUMN activity_images.activity_id IS
    'The activity this image belongs to (FK on the public uuid).';
COMMENT ON COLUMN activity_images.source IS
    'Where the image came from; FK to image_sources.value (uploaded today, strava later).';
COMMENT ON COLUMN activity_images.original_filename IS
    'The file name the uploader sent it under (display); NULL when not applicable.';
COMMENT ON COLUMN activity_images.stored_name IS
    'File name of the stored bytes under uploads/<user_id>/images/ (the row uuid plus its media-type extension).';
COMMENT ON COLUMN activity_images.source_url IS
    'Remote URL the image was fetched from, for future provider fetches; NULL today.';
COMMENT ON COLUMN activity_images.bytes IS
    'Size of the stored file in bytes (display and sanity).';

-- List queries always read a single activity's live images.
CREATE INDEX activity_images_activity_id_idx
    ON activity_images (activity_id) WHERE deleted_at IS NULL;

CREATE TRIGGER activity_images_set_updated_at
    BEFORE UPDATE ON activity_images
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- migrate:down

DROP TRIGGER IF EXISTS activity_images_set_updated_at ON activity_images;
DROP TABLE activity_images;
DROP TABLE image_sources;
