-- M24a: cached per-activity weather snapshots (opt-in, display-only).
--   * ``activity_weather``: at most one live row per activity — the hourly
--     snapshot fetched from Open-Meteo when the user asked for weather on the
--     detail page. The series is a display-only blob that the client always
--     reads whole and never queries into, so it is stored in one standard-SQL
--     ``json`` column (an array of hourly points); lat/lon record the point it
--     was measured for. Re-opening a page never re-fetches: the row is reused
--     until the activity itself is deleted (FK cascade).

-- migrate:up

CREATE TABLE activity_weather (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        uuid NOT NULL UNIQUE,
    activity_id uuid NOT NULL REFERENCES activities (uuid) ON DELETE CASCADE,
    lat         double precision NOT NULL CHECK (lat >= -90 AND lat <= 90),
    lon         double precision NOT NULL CHECK (lon >= -180 AND lon <= 180),
    fetched_at  timestamptz NOT NULL DEFAULT now(),
    data        json NOT NULL CHECK (json_typeof(data) = 'array'),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz NULL
);

COMMENT ON TABLE activity_weather IS
    'Cached weather snapshots per activity (M24). Fetched on demand from Open-Meteo when the user opens "Show weather"; re-opened pages reuse this row instead of fetching again. Display-only: nothing else reads it.';
COMMENT ON COLUMN activity_weather.uuid IS
    'Public identifier exposed by the API (generated by it).';
COMMENT ON COLUMN activity_weather.activity_id IS
    'The activity the snapshot was measured for (FK on the public uuid); at most one live row per activity.';
COMMENT ON COLUMN activity_weather.lat IS
    'Latitude (WGS84) of the point the snapshot covers — the activity''s first GPS trackpoint.';
COMMENT ON COLUMN activity_weather.lon IS
    'Longitude (WGS84) of the point the snapshot covers.';
COMMENT ON COLUMN activity_weather.fetched_at IS
    'When the upstream fetch happened (the row is immutable, so this equals created_at; kept explicit because it names the data''s age for display).';
COMMENT ON COLUMN activity_weather.data IS
    'The hourly snapshot as a JSON array of objects: time (ISO 8601 UTC), temperature_c, apparent_temperature_c, relative_humidity_pct, dew_point_c, weather_code (WMO). Values are null-safe: missing upstream fields stay null.';

-- At most one live snapshot per activity (soft-delete-aware: a deleted row
-- would otherwise block re-fetching after the user clears it).
CREATE UNIQUE INDEX activity_weather_activity_id_uq
    ON activity_weather (activity_id) WHERE deleted_at IS NULL;

CREATE TRIGGER activity_weather_set_updated_at
    BEFORE UPDATE ON activity_weather
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- migrate:down

DROP TRIGGER IF EXISTS activity_weather_set_updated_at ON activity_weather;
DROP TABLE activity_weather;
