-- Provider infrastructure: external data sources (Strava first; Garmin,
-- Polar, ... follow the same pattern).
--
--   * ``providers`` is the reference table for the provider value set.
--   * ``provider_accounts`` links one of a local user's OWN third-party
--     profiles (external identity + OAuth credentials + sync state) to a
--     local account — one row per (user, provider).
--   * ``activities`` gains a nullable ``provider`` reference and an
--     ``external_activity_id`` for dedup; ``source_format`` becomes
--     nullable so it describes the file/export format only (NULL for
--     provider-fetched activities).

-- migrate:up

CREATE TABLE providers (
    value         text PRIMARY KEY,
    description   text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE providers IS
    'Reference table of external data providers (e.g. Strava). Rows are seeded and immutable.';
COMMENT ON COLUMN providers.value IS
    'Provider code; the public API value and the FK target (e.g. strava).';
COMMENT ON COLUMN providers.description IS
    'Human-readable label for UI display (e.g. Strava).';

INSERT INTO providers (value, description) VALUES
    ('strava', 'Strava');

CREATE TABLE provider_accounts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          uuid NOT NULL REFERENCES users (uuid) ON DELETE CASCADE,
    provider         text NOT NULL REFERENCES providers (value),
    external_user_id text NOT NULL,
    display_name     text NULL,
    refresh_token    text NOT NULL,
    access_token     text NOT NULL,
    token_expires_at timestamptz NOT NULL,
    scope            text NOT NULL,
    last_sync_at     timestamptz NULL,
    sync_cursor      text NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz NULL,
    CONSTRAINT provider_accounts_user_id_provider_key UNIQUE (user_id, provider)
);

CREATE TRIGGER provider_accounts_set_updated_at
    BEFORE UPDATE ON provider_accounts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE provider_accounts IS
    'One of a local user''s connected third-party profiles: the user''s own external identity, OAuth credentials, and sync state for one provider.';
COMMENT ON COLUMN provider_accounts.user_id IS 'Owning local account.';
COMMENT ON COLUMN provider_accounts.provider IS
    'FK to providers.value (e.g. strava); unique per user.';
COMMENT ON COLUMN provider_accounts.external_user_id IS
    'The user''s own identity on the provider (e.g. Strava athlete id), as a string.';
COMMENT ON COLUMN provider_accounts.display_name IS
    'Display name of the external profile, for the UI.';
COMMENT ON COLUMN provider_accounts.refresh_token IS
    'Long-lived OAuth refresh token (it rotates on refresh; the latest is stored). Never exposed via the API.';
COMMENT ON COLUMN provider_accounts.access_token IS
    'Cached short-lived OAuth access token (6 hours on Strava). Never exposed via the API.';
COMMENT ON COLUMN provider_accounts.token_expires_at IS
    'Expiry of the cached access token (UTC).';
COMMENT ON COLUMN provider_accounts.scope IS
    'Space-delimited list of the scopes the user granted.';
COMMENT ON COLUMN provider_accounts.last_sync_at IS
    'When the last activity sync completed (UTC).';
COMMENT ON COLUMN provider_accounts.sync_cursor IS
    'Provider-specific opaque pagination resume point (Strava: unix timestamp of the last page boundary).';

-- activities: provider reference + external id for dedup; source_format is
-- the file/export format only from now on (NULL for provider-fetched rows).
ALTER TABLE activities ALTER COLUMN source_format DROP NOT NULL;
COMMENT ON COLUMN activities.source_format IS
    'File/export format (gpx/tcx/fit/apple_health); NULL when fetched from a provider API.';

ALTER TABLE activities
    ADD COLUMN provider text NULL REFERENCES providers (value);
COMMENT ON COLUMN activities.provider IS
    'Provider the activity was fetched from; FK to providers.value; NULL for file imports.';

ALTER TABLE activities
    ADD COLUMN external_activity_id text NULL;
COMMENT ON COLUMN activities.external_activity_id IS
    'The activity''s id on the provider, for dedup; NULL for file imports.';

CREATE UNIQUE INDEX activities_provider_external_activity_id_key
    ON activities (provider, external_activity_id)
    WHERE provider IS NOT NULL AND external_activity_id IS NOT NULL;
COMMENT ON INDEX activities_provider_external_activity_id_key IS
    'A provider activity is imported at most once per (provider, external id).';

-- migrate:down

DROP INDEX activities_provider_external_activity_id_key;
ALTER TABLE activities DROP COLUMN external_activity_id;
ALTER TABLE activities DROP COLUMN provider;
COMMENT ON COLUMN activities.source_format IS
    'Format of the imported file: gpx, tcx, fit, or apple_health.';
ALTER TABLE activities ALTER COLUMN source_format SET NOT NULL;

DROP TABLE provider_accounts;
DROP TABLE providers;
