"""User account model."""

from sqlalchemy import Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import IntIdUuidModel, TimestampMixin


class User(IntIdUuidModel, TimestampMixin):
    """An application account.

    ``id`` is the internal integer primary key; ``uuid`` is the public
    identifier (UUIDv4 generated by the API) used in URLs and tokens.

    ``email`` is always stored normalized (trimmed, lower-case); uniqueness is
    therefore case-insensitive by construction.
    """

    __tablename__ = "users"

    first_name: Mapped[str] = mapped_column(Text, nullable=False)
    last_name: Mapped[str] = mapped_column(Text, nullable=False)
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)

    def __repr__(self) -> str:
        return f"User(id={self.id}, uuid={self.uuid}, email={self.email!r})"
