"""Mapping between activity models and API views."""

from datetime import datetime
from uuid import UUID

from app.imports.parsed import ParsedTrackpoint
from app.models.activity import Activity
from app.models.activity_split import ActivitySplit
from app.models.activity_trackpoint import ActivityTrackpoint
from app.models.cycling_activity import CyclingActivity
from app.models.rowing_activity import RowingActivity
from app.models.running_activity import RunningActivity
from app.models.strength_activity import StrengthActivity
from app.schemas.units import (
    UnitSystem,
    display_altitude,
    display_distance,
    display_elevation_gain,
    display_pace_seconds,
    display_speed,
    display_weight,
)
from app.schemas.views.activity_views import (
    ActivityCountView,
    ActivityDetailView,
    ActivityPeriodSummaryView,
    ActivitySummaryView,
    CyclingMetricsView,
    DistanceTrendPointView,
    HrZoneView,
    RowingMetricsView,
    RunningMetricsView,
    SplitView,
    StrengthMetricsView,
    TrackpointView,
    WalkingMetricsView,
)
from app.services.activity_stats import HrZoneStats, PeriodSummary, SplitStats, TrendPoint


class ActivityMapper:
    """Translates activity data between models and views."""

    @staticmethod
    def create_activity(
        activity_uuid: UUID,
        user_id: UUID,
        sport_type: str,
        name: str,
        description: str | None,
        started_at: datetime,
        ended_at: datetime,
        duration_seconds: int,
        moving_seconds: int | None,
        distance_m: float | None,
        calories_kcal: float | None,
        elevation_gain_m: float | None,
        heart_rate_min_bpm: int | None,
        heart_rate_avg_bpm: int | None,
        heart_rate_max_bpm: int | None,
        cadence_avg_rpm: int | None,
        source_format: str | None,
        provider: str | None = None,
        external_activity_id: str | None = None,
        original_filename: str | None = None,
        file_path: str | None = None,
    ) -> Activity:
        """Build a new Activity model (public uuid generated by the import service)."""
        return Activity(
            uuid=activity_uuid,
            user_id=user_id,
            sport_type=sport_type,
            name=name,
            description=description,
            started_at=started_at,
            ended_at=ended_at,
            duration_seconds=duration_seconds,
            moving_seconds=moving_seconds,
            distance_m=distance_m,
            calories_kcal=calories_kcal,
            elevation_gain_m=elevation_gain_m,
            heart_rate_min_bpm=heart_rate_min_bpm,
            heart_rate_avg_bpm=heart_rate_avg_bpm,
            heart_rate_max_bpm=heart_rate_max_bpm,
            cadence_avg_rpm=cadence_avg_rpm,
            source_format=source_format,
            provider=provider,
            external_activity_id=external_activity_id,
            original_filename=original_filename,
            file_path=file_path,
        )

    @staticmethod
    def create_trackpoints(
        activity_id: UUID, points: list[ParsedTrackpoint]
    ) -> list[ActivityTrackpoint]:
        """Build the trackpoint rows for one parsed activity."""
        rows: list[ActivityTrackpoint] = []
        for seq, point in enumerate(points):
            rows.append(
                ActivityTrackpoint(
                    activity_id=activity_id,
                    seq=seq,
                    recorded_at=point.recorded_at,
                    lat=point.lat,
                    lon=point.lon,
                    altitude_m=point.altitude_m,
                    heart_rate_bpm=point.heart_rate_bpm,
                    cadence_rpm=point.cadence_rpm,
                    speed_mps=point.speed_mps,
                    power_w=point.power_w,
                )
            )
        return rows

    @staticmethod
    def create_splits(activity_id: UUID, splits: list[SplitStats]) -> list[ActivitySplit]:
        """Build the split rows from computed split statistics."""
        return [
            ActivitySplit(
                activity_id=activity_id,
                split_type=split.split_type,
                split_index=split.split_index,
                duration_seconds=split.duration_seconds,
                pace_seconds=split.pace_seconds,
                heart_rate_avg_bpm=split.heart_rate_avg_bpm,
                cadence_avg_rpm=split.cadence_avg_rpm,
            )
            for split in splits
        ]

    @staticmethod
    def create_running_activity(
        activity_id: UUID,
        avg_pace_s_per_km: float | None,
        min_pace_s_per_km: float | None,
        max_pace_s_per_km: float | None,
    ) -> RunningActivity:
        """Build the running metric row."""
        return RunningActivity(
            activity_id=activity_id,
            avg_pace_s_per_km=avg_pace_s_per_km,
            min_pace_s_per_km=min_pace_s_per_km,
            max_pace_s_per_km=max_pace_s_per_km,
        )

    @staticmethod
    def create_cycling_activity(
        activity_id: UUID, power_avg_w: int | None, power_max_w: int | None
    ) -> CyclingActivity:
        """Build the cycling metric row."""
        return CyclingActivity(
            activity_id=activity_id, power_avg_w=power_avg_w, power_max_w=power_max_w
        )

    @staticmethod
    def create_rowing_activity(
        activity_id: UUID,
        stroke_rate_avg_spm: int | None = None,
        stroke_rate_min_spm: int | None = None,
        stroke_rate_max_spm: int | None = None,
        split_500m_seconds: float | None = None,
    ) -> RowingActivity:
        """Build the rowing metric row."""
        return RowingActivity(
            activity_id=activity_id,
            stroke_rate_avg_spm=stroke_rate_avg_spm,
            stroke_rate_min_spm=stroke_rate_min_spm,
            stroke_rate_max_spm=stroke_rate_max_spm,
            split_500m_seconds=split_500m_seconds,
        )

    @staticmethod
    def create_strength_activity(activity_id: UUID) -> StrengthActivity:
        """Build the strength metric row (empty until sets are entered)."""
        return StrengthActivity(activity_id=activity_id, total_sets=0, total_exercises=0)

    @staticmethod
    def to_summary_view(activity: Activity, units: UnitSystem) -> ActivitySummaryView:
        """Map an ORM activity to its list-feed view.

        Distance and elevation are converted into the caller's display unit
        system (``units``); calories stay kcal.
        """
        return ActivitySummaryView(
            id=activity.uuid,
            sport_type=activity.sport_type,
            name=activity.name,
            started_at=activity.started_at,
            duration_seconds=activity.duration_seconds,
            moving_seconds=activity.moving_seconds,
            distance=display_distance(activity.distance_m, units),
            calories_kcal=activity.calories_kcal,
            elevation_gain=display_elevation_gain(activity.elevation_gain_m, units),
            heart_rate_avg_bpm=activity.heart_rate_avg_bpm,
            provider=activity.provider,
        )

    @staticmethod
    def to_period_summary_view(
        summary: PeriodSummary, units: UnitSystem
    ) -> ActivityPeriodSummaryView:
        """Map the raw (SI) period summary to its view.

        Unit-bearing values are converted into ``units``; nulls pass through
        unchanged (a metric with no data in the period stays null).
        """
        return ActivityPeriodSummaryView(
            units=units.value,
            activity_count=ActivityCountView(
                total=summary.total_activities, by_sport_type=dict(summary.by_sport_type)
            ),
            moving_seconds_total=summary.moving_seconds_total,
            distance=display_distance(summary.distance_m, units),
            elevation_gain=display_elevation_gain(summary.elevation_gain_m, units),
            calories_kcal=summary.calories_kcal,
            avg_heart_rate_bpm=summary.avg_heart_rate_bpm,
            weight_lifted=display_weight(summary.weight_lifted_kg, units),
            distance_trend=[
                ActivityMapper._trend_point_view(point, units) for point in summary.trend_points
            ],
        )

    @staticmethod
    def _trend_point_view(point: TrendPoint, units: UnitSystem) -> DistanceTrendPointView:
        """Map one raw (SI) trend bucket to its view.

        A trend point always carries a distance — gaps are zero-filled, never
        null — so the conversion cannot come back None.
        """
        value = display_distance(point.distance_m, units)
        assert value is not None  # invariant of TrendPoint (see above)
        return DistanceTrendPointView(start=point.start, value=value)

    @staticmethod
    def to_split_view(split: ActivitySplit) -> SplitView:
        """Map an ORM split to its view."""
        return SplitView(
            split_type=split.split_type,
            split_index=split.split_index,
            duration_seconds=split.duration_seconds,
            pace_seconds=split.pace_seconds,
            heart_rate_avg_bpm=split.heart_rate_avg_bpm,
            cadence_avg_rpm=split.cadence_avg_rpm,
        )

    @staticmethod
    def to_trackpoint_view(point: ActivityTrackpoint, units: UnitSystem) -> TrackpointView:
        """Map an ORM trackpoint to its view (altitude/speed in the caller's units)."""
        return TrackpointView(
            seq=point.seq,
            recorded_at=point.recorded_at,
            lat=point.lat,
            lon=point.lon,
            altitude=display_altitude(point.altitude_m, units),
            heart_rate_bpm=point.heart_rate_bpm,
            cadence_rpm=point.cadence_rpm,
            speed=display_speed(point.speed_mps, units),
            power_w=point.power_w,
        )

    @staticmethod
    def _walking_avg_pace_s_per_km(activity: Activity) -> float | None:
        """Average walking pace in s/km from the stored moving time and distance.

        None when either is missing or zero — a walk without GPS (or with no
        moving time) simply has no pace, mirroring how running paces stay null.
        """
        if activity.moving_seconds is None or not activity.distance_m:
            return None
        seconds_per_km = activity.moving_seconds / (activity.distance_m / 1000.0)
        return round(seconds_per_km, 1)

    @staticmethod
    def to_detail_view(
        activity: Activity,
        splits: list[ActivitySplit],
        zones: HrZoneStats | None,
        running: RunningActivity | None,
        cycling: CyclingActivity | None,
        rowing: RowingActivity | None,
        strength: StrengthActivity | None,
        units: UnitSystem,
    ) -> ActivityDetailView:
        """Map an activity and its derived rows to the detail view.

        ``splits`` is already filtered by the caller's unit system (the service
        does that); distance, elevation, paces and weight are converted into it.

        Walking has no metric row: its pace is derived at view time from the
        stored moving time and distance (see ``_walking_avg_pace_s_per_km``).
        """
        walking_pace = (
            ActivityMapper._walking_avg_pace_s_per_km(activity)
            if activity.sport_type == "walking"
            else None
        )
        return ActivityDetailView(
            id=activity.uuid,
            sport_type=activity.sport_type,
            name=activity.name,
            description=activity.description,
            started_at=activity.started_at,
            ended_at=activity.ended_at,
            duration_seconds=activity.duration_seconds,
            moving_seconds=activity.moving_seconds,
            distance=display_distance(activity.distance_m, units),
            calories_kcal=activity.calories_kcal,
            elevation_gain=display_elevation_gain(activity.elevation_gain_m, units),
            heart_rate_min_bpm=activity.heart_rate_min_bpm,
            heart_rate_avg_bpm=activity.heart_rate_avg_bpm,
            heart_rate_max_bpm=activity.heart_rate_max_bpm,
            cadence_avg_rpm=activity.cadence_avg_rpm,
            provider=activity.provider,
            source_format=activity.source_format,
            original_filename=activity.original_filename,
            created_at=activity.created_at,
            units=units.value,
            splits=[ActivityMapper.to_split_view(split) for split in splits],
            heart_rate_zones=(
                HrZoneView(
                    zone_1_seconds=zones.zone_1_seconds,
                    zone_2_seconds=zones.zone_2_seconds,
                    zone_3_seconds=zones.zone_3_seconds,
                    zone_4_seconds=zones.zone_4_seconds,
                    zone_5_seconds=zones.zone_5_seconds,
                )
                if zones is not None
                else None
            ),
            running=(
                RunningMetricsView(
                    avg_pace_seconds=display_pace_seconds(running.avg_pace_s_per_km, units),
                    min_pace_seconds=display_pace_seconds(running.min_pace_s_per_km, units),
                    max_pace_seconds=display_pace_seconds(running.max_pace_s_per_km, units),
                )
                if running is not None
                else None
            ),
            # Emitted for every walk, even one without distance (pace then null).
            walking=(
                WalkingMetricsView(avg_pace_seconds=display_pace_seconds(walking_pace, units))
                if activity.sport_type == "walking"
                else None
            ),
            cycling=(
                CyclingMetricsView(
                    power_avg_w=cycling.power_avg_w,
                    power_max_w=cycling.power_max_w,
                )
                if cycling is not None
                else None
            ),
            rowing=(
                RowingMetricsView(
                    stroke_rate_avg_spm=rowing.stroke_rate_avg_spm,
                    stroke_rate_min_spm=rowing.stroke_rate_min_spm,
                    stroke_rate_max_spm=rowing.stroke_rate_max_spm,
                    split_500m_seconds=rowing.split_500m_seconds,
                )
                if rowing is not None
                else None
            ),
            strength=(
                StrengthMetricsView(
                    total_sets=strength.total_sets,
                    total_exercises=strength.total_exercises,
                    total_weight=display_weight(strength.total_weight_kg, units),
                )
                if strength is not None
                else None
            ),
        )
